#!/bin/bash #this line is for highlighting purpose only
# A_ALARM section ######################################################
# numbers

a_alarm	будильник 													# на какое время?
a_alarm	Time:7														& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:7 Time:30												& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:7 часов												& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:7 часов утра											& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:7 часов Time:30 минут									& p_time


a_alarm	будильник 													# на какое время?
a_alarm	на Time:7													& p_time

a_alarm	будильник 													# на какое время?
a_alarm	на Time:7 Time:30											& p_time

a_alarm	будильник 													# на какое время?
a_alarm	на Time:7 часов Time:30 минут								& p_time


a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:7											& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:7 Time:30									& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:7 часов Time:30 минут						& p_time


a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:7									& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:7 Time:30							& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:7 часов Time:30 минут				& p_time



# 1 txtnums

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь													& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь Time:30											& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь часов												& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь часов утра										& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь часов Time:30 минут								& p_time


a_alarm	будильник 													# на какое время?
a_alarm	на Time:семь												& p_time

a_alarm	будильник 													# на какое время?
a_alarm	на Time:семь Time:30										& p_time

a_alarm	будильник 													# на какое время?
a_alarm	на Time:семь часов Time:30 минут							& p_time


a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:семь										& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:семь Time:30								& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:семь часов Time:30 минут					& p_time


a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:семь								& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:семь Time:30						& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:семь часов Time:30 минут			& p_time


# 2 txtnums

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь													& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь Time:тридцать										& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь часов												& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь часов утра										& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь часов Time:тридцать минут							& p_time


a_alarm	будильник 													# на какое время?
a_alarm	на Time:семь												& p_time

a_alarm	будильник 													# на какое время?
a_alarm	на Time:семь Time:тридцать									& p_time

a_alarm	будильник 													# на какое время?
a_alarm	на Time:семь часов Time:тридцать минут						& p_time


a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:семь										& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:семь Time:тридцать							& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:семь часов Time:тридцать минут				& p_time


a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:семь								& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:семь Time:тридцать				& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:семь часов Time:тридцать минут	& p_time


# cancellation, 1 s_change word

a_alarm	будильник 													# на какое время?
a_call	нет позвони васе											& p_time

a_alarm	будильник 													# на какое время?
a_sms	нет напиши смс												& p_time

a_alarm	будильник 													# на какое время?
a_email	нет напиши письмо											& p_time

a_alarm	будильник 													# на какое время?
a_search	нет найди мне статью									& p_time

a_alarm	будильник 													# на какое время?
a_site	нет открой мне сайт											& p_time

a_alarm	будильник 													# на какое время?
a_alarm	нет поставь будильник										& p_time

a_alarm	будильник 													# на какое время?
a_balance	нет покажи баланс										& p_time

a_alarm	будильник 													# на какое время?
a_cancel	отмена													& p_time


# cancellation, 2 s_change words

a_alarm	будильник 													# на какое время?
a_call	хотя нет позвони васе										& p_time

a_alarm	будильник 													# на какое время?
a_sms	хотя нет напиши смс											& p_time

a_alarm	будильник 													# на какое время?
a_email	хотя нет напиши письмо										& p_time

a_alarm	будильник 													# на какое время?
a_search	хотя нет найди мне статью								& p_time

a_alarm	будильник 													# на какое время?
a_site	хотя нет открой мне сайт									& p_time

a_alarm	будильник 													# на какое время?
a_alarm	хотя нет поставь будильник									& p_time

a_alarm	будильник 													# на какое время?
a_balance	хотя нет покажи баланс									& p_time


# cancellation, 3 s_change words

a_alarm	будильник 													# на какое время?
a_cancel	отмена													& p_time

a_alarm	будильник 													# на какое время?
a_call	хотя нет лучше позвони васе									& p_time

a_alarm	будильник 													# на какое время?
a_sms	хотя нет лучше напиши смс									& p_time

a_alarm	будильник 													# на какое время?
a_email	хотя нет лучше напиши письмо								& p_time

a_alarm	будильник 													# на какое время?
a_search	хотя нет лучше найди мне статью							& p_time

a_alarm	будильник 													# на какое время?
a_site	хотя нет лучше открой мне сайт								& p_time

a_alarm	будильник 													# на какое время?
a_alarm	хотя нет лучше поставь будильник							& p_time

a_alarm	будильник 													# на какое время?
a_balance	хотя нет лучше покажи баланс							& p_time

