#!/bin/bash #this line is for highlighting purpose only
#
# a_search: найди в яндексе ... 
# a_search: найди на google com ...
# a_search: найди на google точка com ...
# a_search: найди пожалуйста на википедии что такое компьютер ...
#
########################################################################
# A collection of marked user commands for the following commands types:
# a_call	call to smb
# a_sms		send sms to smb
# a_email	send email to smb
# a_search	serch smt on the web
# a_site	launch a site in browser
# a_alarm	set an alarm for particular time
# a_balance	check how much money you have on your account
########################################################################


# A_CALL section #######################################################

# with name or number

a_call	позвони						# кому позвонить?
a_call	васе						& p_name

a_call	позвони						# кому позвонить?
a_call	василию ивановичу			& p_name

a_call	позвони						# кому позвонить?
a_call	василию ивановичу петрову	& p_name

a_call	позвони						# кому позвонить?
a_call	100							& p_number

a_call	позвони						# кому позвонить?
a_call	по номеру 100				& p_number

a_call	позвони						# кому позвонить?
a_call	по телефонному номеру 100	& p_number


# with a_call + name or number

a_call	позвони								# кому позвонить?
a_call	позвони васе						& p_name

a_call	позвони								# кому позвонить?
a_call	позвони василию ивановичу			& p_name

a_call	позвони								# кому позвонить?
a_call	позвони василию ивановичу петрову	& p_name

a_call	позвони								# кому позвонить?
a_call	позвони 100							& p_number

a_call	позвони								# кому позвонить?
a_call	позвони по номеру 100				& p_number

a_call	позвони								# кому позвонить?
a_call	позвони по телефонному номеру 100	& p_number


# with ambiguous "набери" + name or number

a_call	позвони								# кому позвонить?
a_call	набери васю							& p_name

a_call	позвони								# кому позвонить?
a_call	набери василия ивановича			& p_name

a_call	позвони								# кому позвонить?
a_call	набери василия ивановича петрова	& p_name

a_call	позвони								# кому позвонить?
a_call	набери 100							& p_number

a_call	позвони								# кому позвонить?
a_call	набери номер 100					& p_number

a_call	позвони								# кому позвонить?
a_call	набери телефонный номер 100			& p_number



###
# cancellation, 1 s_change word

a_call	позвони								# кому?
a_call	нет позвони васе					& p_name

a_call	позвони								# кому?
a_sms	нет напиши смс						& p_name

a_call	позвони								# кому?
a_email	нет напиши письмо					& p_name

a_call	позвони								# кому?
a_search	нет найди мне статью			& p_name

a_call	позвони								# кому?
a_site	нет открой мне сайт					& p_name

a_call	позвони								# кому?
a_alarm	нет поставь будильник				& p_name

a_call	позвони								# кому?
a_balance	нет покажи баланс				& p_name

a_call	позвони								# кому?
a_cancel	отмена							& p_name


# cancellation, 2 s_change words

a_call	позвони								# кому?
a_call	хотя нет позвони васе				& p_name

a_call	позвони								# кому?
a_sms	хотя нет напиши смс					& p_name

a_call	позвони								# кому?
a_email	хотя нет напиши письмо				& p_name

a_call	позвони								# кому?
a_search	хотя нет найди мне статью		& p_name

a_call	позвони								# кому?
a_site	хотя нет открой мне сайт			& p_name

a_call	позвони								# кому?
a_alarm	хотя нет поставь будильник			& p_name

a_call	позвони								# кому?
a_balance	хотя нет покажи баланс			& p_name


# cancellation, 3 s_change words

a_call	позвони								# кому?
a_call	хотя нет лучше позвони васе			& p_name

a_call	позвони								# кому?
a_sms	хотя нет лучше напиши смс			& p_name

a_call	позвони								# кому?
a_email	хотя нет лучше напиши письмо		& p_name

a_call	позвони								# кому?
a_search	хотя нет лучше найди мне статью	& p_name

a_call	позвони								# кому?
a_site	хотя нет лучше открой мне сайт		& p_name

a_call	позвони								# кому?
a_alarm	хотя нет лучше поставь будильник	& p_name

a_call	позвони								# кому?
a_balance	хотя нет лучше покажи баланс	& p_name







# A_SMS section ########################################################

# with text
a_sms	смс													# что написать?
a_sms	_привет												& quote

a_sms	смс													# что написать?
a_sms	_привет _вася										& quote

a_sms	смс													# что написать?
a_sms	_привет _как _дела									& quote

a_sms	смс													# что написать?
a_sms	_привет _вася _как _дела							& quote


# with ambiguous "напиши" and text

a_sms	смс													# что написать?
a_sms	напиши _привет										& quote

a_sms	смс													# что написать?
a_sms	напиши _привет _вася								& quote

a_sms	смс													# что написать?
a_sms	напиши _привет _как _дела							& quote

a_sms	смс													# что написать?
a_sms	напиши _привет _вася _как _дела						& quote


# with s_text and text

a_sms	смс													# что написать?
a_sms	с текстом _привет									& quote

a_sms	смс													# что написать?
a_sms	с текстом _привет _вася								& quote

a_sms	смс													# что написать?
a_sms	с текстом _привет _как _дела						& quote

a_sms	смс													# что написать?
a_sms	с текстом _привет _вася _как _дела					& quote


# with name

a_sms	смс													# кому?
a_sms	васе												& p_name

a_sms	смс													# кому?
a_sms	васе петрову										& p_name

a_sms	смс													# кому?
a_sms	василию ивановичу петрову							& p_name


# with a_sms + name

a_sms	смс													# кому?
a_sms	смс васе											& p_name

a_sms	смс													# кому?
a_sms	смс васе петрову									& p_name

a_sms	смс													# кому?
a_sms	смс василию ивановичу петрову						& p_name


# with ambiguous "отправь" + name

a_sms	смс													# кому?
a_sms	отправь васе										& p_name

a_sms	смс													# кому?
a_sms	отправь васе петрову								& p_name

a_sms	смс													# кому?
a_sms	отправь василию ивановичу петрову					& p_name


# with ambiguous "отправь" + a_sms and name

a_sms	смс													# кому?
a_sms	отправь смс васе									& p_name

a_sms	смс													# кому?
a_sms	отправь смс васе петрову							& p_name

a_sms	смс													# кому?
a_sms	отправь смс василию ивановичу петрову				& p_name


# with full command

a_sms	смс													# кому?
a_sms	смс васе с текстом _привет							& p_name

a_sms	смс													# кому?
a_sms	смс василию ивановичу с текстом _привет				& p_name

a_sms	смс													# кому?
a_sms	смс василию ивановичу петрову с текстом _привет		& p_name

#####
# complicated text (action keywords included)

a_sms	смс													# что написать?
a_sms	_почему _не _звонишь								& quote

a_sms	смс													# что написать?
a_sms	_отправь _сообщение _васе							& quote

a_sms	смс													# что написать?
a_sms	_получил _твое _письмо								& quote

a_sms	смс													# что написать?
a_sms	_разбуди _меня _завтра _в _7						& quote

a_sms	смс													# что написать?
a_sms	_открой _браузер									& quote

a_sms	смс													# что написать?
a_sms	_пополни _мой _баланс								& quote

a_sms	смс													# что написать?
a_sms	_проверь _баланс									& quote


# complicated text (params keywords included)

a_sms	смс													# что написать?
a_sms	_привет _от _саши									& quote

a_sms	смс													# что написать?
a_sms	_позвони _на _номер _8 _917 _123 _45 _67			& quote

a_sms	смс													# что написать?
a_sms	_sasha _собака _gmail.com							& quote

a_sms	смс													# что написать?
a_sms	_зайди _на _yandex.ru								& quote

a_sms	смс													# что написать?
a_sms	_завтра _буду _в _7 _часов							& quote

#####
# complicated text: action keywords included + a_sms

a_sms	смс													# что написать?
a_sms	напиши _почему _не _звонишь							& quote

a_sms	смс													# что написать?
a_sms	напиши _напиши _мне									& quote

a_sms	смс													# что написать?
a_sms	напиши _получил _твое _письмо						& quote

a_sms	смс													# что написать?
a_sms	напиши _разбуди _меня _завтра _в _7					& quote

a_sms	смс													# что написать?
a_sms	напиши _открой _браузер								& quote

a_sms	смс													# что написать?
a_sms	напиши _пополни _мой _баланс						& quote

a_sms	смс													# что написать?
a_sms	напиши _проверь _баланс								& quote


# complicated text: params keywords included + s_text

a_sms	смс													# что написать?
a_sms	напиши _привет _от _саши							& quote

a_sms	смс													# что написать?
a_sms	напиши _позвони _на _номер _8 _917 _123 _45 _67		& quote

a_sms	смс													# что написать?
a_sms	напиши _sasha _собака _gmail.com					& quote

a_sms	смс													# что написать?
a_sms	напиши _зайди _на _yandex.ru						& quote

a_sms	смс													# что написать?
a_sms	напиши _завтра _буду _в _7 _часов					& quote


# cancellation, 1 s_change word

a_sms	смс													# что написать?
a_call	нет позвони васе									& quote

a_sms	смс													# что написать?
a_sms	нет напиши смс										& quote

a_sms	смс													# что написать?
a_email	нет напиши письмо									& quote

a_sms	смс													# что написать?
a_search	нет найди мне статью							& quote

a_sms	смс													# что написать?
a_site	нет открой мне сайт									& quote

a_sms	смс													# что написать?
a_alarm	нет поставь будильник								& quote

a_sms	смс													# что написать?
a_balance	нет покажи баланс								& quote

a_sms	смс													# что написать?
a_cancel	отмена											& quote


# cancellation, 2 s_change words

a_sms	смс													# что написать?
a_call	хотя нет позвони васе								& quote

a_sms	смс													# что написать?
a_sms	хотя нет напиши смс									& quote

a_sms	смс													# что написать?
a_email	хотя нет напиши письмо								& quote

a_sms	смс													# что написать?
a_search	хотя нет найди мне статью						& quote

a_sms	смс													# что написать?
a_site	хотя нет открой мне сайт							& quote

a_sms	смс													# что написать?
a_alarm	хотя нет поставь будильник							& quote

a_sms	смс													# что написать?
a_balance	хотя нет покажи баланс							& quote


# cancellation, 3 s_change words

a_sms	смс													# что написать?
a_call	хотя нет лучше позвони васе							& quote

a_sms	смс													# что написать?
a_sms	хотя нет лучше напиши смс							& quote

a_sms	смс													# что написать?
a_email	хотя нет лучше напиши письмо						& quote

a_sms	смс													# что написать?
a_search	хотя нет лучше найди мне статью					& quote

a_sms	смс													# что написать?
a_site	хотя нет лучше открой мне сайт						& quote

a_sms	смс													# что написать?
a_alarm	хотя нет лучше поставь будильник					& quote

a_sms	смс													# что написать?
a_balance	хотя нет лучше покажи баланс					& quote





# A_EMAIL section ######################################################

# with text
a_email	письмо												# что написать?
a_email	_привет												& quote

a_email	письмо												# что написать?
a_email	_привет _вася										& quote

a_email	письмо												# что написать?
a_email	_привет _как _дела									& quote

a_email	письмо												# что написать?
a_email	_привет _вася _как _дела


# with ambiguous "напиши" and text

a_email	письмо												# что написать?
a_email	напиши _привет										& quote

a_email	письмо												# что написать?
a_email	напиши _привет _вася								& quote

a_email	письмо												# что написать?
a_email	напиши _привет _как _дела							& quote

a_email	письмо												# что написать?
a_email	напиши _привет _вася _как _дела


# with s_text and text

a_email	письмо												# что написать?
a_email	с текстом _привет									& quote

a_email	письмо												# что написать?
a_email	с текстом _привет _вася								& quote

a_email	письмо												# что написать?
a_email	с текстом _привет _как _дела						& quote

a_email	письмо												# что написать?
a_email	с текстом _привет _вася _как _дела


# with name

a_email	письмо												# кому?
a_email	васе												& p_name

a_email	письмо												# кому?
a_email	васе петрову										& p_name

a_email	письмо												# кому?
a_email	василию ивановичу петрову							& p_name


# with a_email + name

a_email	письмо												# кому?
a_email	письмо васе											& p_name

a_email	письмо												# кому?
a_email	письмо васе петрову									& p_name

a_email	письмо												# кому?
a_email	письмо василию ивановичу петрову					& p_name


# with ambiguous "отправь" + name

a_email	письмо												# кому?
a_email	отправь васе										& p_name

a_email	письмо												# кому?
a_email	отправь васе петрову								& p_name

a_email	письмо												# кому?
a_email	отправь василию ивановичу петрову					& p_name


# with ambiguous "отправь" + a_email and name

a_email	письмо												# кому?
a_email	отправь письмо васе									& p_name

a_email	письмо												# кому?
a_email	отправь письмо васе петрову							& p_name

a_email	письмо												# кому?
a_email	отправь письмо василию ивановичу петрову			& p_name


# with full command

a_email	письмо												# кому?
a_email	письмо васе с текстом _привет						& p_name

a_email	письмо												# кому?
a_email	письмо василию ивановичу с текстом _привет			& p_name

a_email	письмо												# кому?
a_email	письмо василию ивановичу петрову с текстом _привет	& p_name

#####
# complicated text (action keywords included)

a_email	письмо												# что написать?
a_email	_почему _не _звонишь								& quote

a_email	письмо												# что написать?
a_email	_отправь _сообщение _васе							& quote

a_email	письмо												# что написать?
a_email	_получил _твое _письмо								& quote

a_email	письмо												# что написать?
a_email	_разбуди _меня _завтра _в _7						& quote

a_email	письмо												# что написать?
a_email	_открой _браузер									& quote

a_email	письмо												# что написать?
a_email	_пополни _мой _баланс								& quote

a_email	письмо												# что написать?
a_email	_проверь _баланс									& quote


# complicated text (params keywords included)

a_email	письмо												# что написать?
a_email	_привет _от _саши									& quote

a_email	письмо												# что написать?
a_email	_позвони _на _номер _8 _917 _123 _45 _67			& quote

a_email	письмо												# что написать?
a_email	_sasha _собака _gmail.com							& quote

a_email	письмо												# что написать?
a_email	_зайди _на _yandex.ru								& quote

a_email	письмо												# что написать?
a_email	_завтра _буду _в _7 _часов							& quote

#####
# complicated text: action keywords included + a_email

a_email	письмо												# что написать?
a_email	напиши _почему _не _звонишь							& quote

a_email	письмо												# что написать?
a_email	напиши _напиши _мне									& quote

a_email	письмо												# что написать?
a_email	напиши _получил _твое _письмо						& quote

a_email	письмо												# что написать?
a_email	напиши _разбуди _меня _завтра _в _7					& quote

a_email	письмо												# что написать?
a_email	напиши _открой _браузер								& quote

a_email	письмо												# что написать?
a_email	напиши _пополни _мой _баланс						& quote

a_email	письмо												# что написать?
a_email	напиши _проверь _баланс


# complicated text: params keywords included + s_text

a_email	письмо												# что написать?
a_email	напиши _привет _от _саши							& quote

a_email	письмо												# что написать?
a_email	напиши _позвони _на _номер _8 _917 _123 _45 _67		& quote

a_email	письмо												# что написать?
a_email	напиши _sasha _собака _gmail.com					& quote

a_email	письмо												# что написать?
a_email	напиши _зайди _на _yandex.ru						& quote

a_email	письмо												# что написать?
a_email	напиши _завтра _буду _в _7 _часов					& quote


# cancellation, 1 s_change word

a_email	письмо												# что написать?
a_call	нет позвони васе									& quote

a_email	письмо												# что написать?
a_sms	нет напиши смс										& quote

a_email	письмо												# что написать?
a_email	нет напиши письмо									& quote

a_email	письмо												# что написать?
a_search	нет найди мне статью							& quote

a_email	письмо												# что написать?
a_site	нет открой мне сайт									& quote

a_email	письмо												# что написать?
a_alarm	нет поставь будильник								& quote

a_email	письмо												# что написать?
a_balance	нет покажи баланс								& quote

a_email	письмо												# что написать?
a_cancel	отмена											& quote


# cancellation, 2 s_change words

a_email	письмо												# что написать?
a_call	хотя нет позвони васе								& quote

a_email	письмо												# что написать?
a_sms	хотя нет напиши смс									& quote

a_email	письмо												# что написать?
a_email	хотя нет напиши письмо								& quote

a_email	письмо												# что написать?
a_search	хотя нет найди мне статью						& quote

a_email	письмо												# что написать?
a_site	хотя нет открой мне сайт							& quote

a_email	письмо												# что написать?
a_alarm	хотя нет поставь будильник							& quote

a_email	письмо												# что написать?
a_balance	хотя нет покажи баланс							& quote


# cancellation, 3 s_change words

a_email	письмо												# что написать?
a_call	хотя нет лучше позвони васе							& quote

a_email	письмо												# что написать?
a_sms	хотя нет лучше напиши смс							& quote

a_email	письмо												# что написать?
a_email	хотя нет лучше напиши письмо						& quote

a_email	письмо												# что написать?
a_search	хотя нет лучше найди мне статью					& quote

a_email	письмо												# что написать?
a_site	хотя нет лучше открой мне сайт						& quote

a_email	письмо												# что написать?
a_alarm	хотя нет лучше поставь будильник					& quote

a_email	письмо												# что написать?
a_balance	хотя нет лучше покажи баланс					& quote




# A_SEARCH section #####################################################

# with 1 search-word					& quote

a_search	поиск													# что нужно найти?
a_search	_дзен													& quote

a_search	поиск													# что нужно найти?
a_search	найди _дзен												& quote

a_search	поиск													# что нужно найти?
a_search	что такое _дзен											& quote

a_search	поиск													# что нужно найти?
a_search	найди что такое _дзен									& quote


# with 1 search-word + source

a_search	поиск													# что нужно найти?
a_search	_дзен в википедии										& quote

a_search	поиск													# что нужно найти?
a_search	найди _дзен в википедии									& quote

a_search	поиск													# что нужно найти?
a_search	что такое _дзен в википедии								& quote

a_search	поиск													# что нужно найти?
a_search	найди что такое _дзен в википедии						& quote


# with source + 1 search-word

a_search	поиск													# что нужно найти?
a_search	википедия _дзен											& quote

a_search	поиск													# что нужно найти?
a_search	найди в википедии _дзен									& quote

a_search	поиск													# что нужно найти?
a_search	найди в википедии статью про _дзен						& quote


#####
# with 2 search-words + source

a_search	поиск													# что нужно найти?
a_search	_дзен _буддизм											& quote

a_search	поиск													# что нужно найти?
a_search	найди _дзен _буддизм									& quote

a_search	поиск													# что нужно найти?
a_search	что такое _дзен _буддизм								& quote

a_search	поиск													# что нужно найти?
a_search	найди что такое _дзен _буддизм							& quote


# with 2 search-words + source

a_search	поиск													# что нужно найти?
a_search	_дзен _буддизм в википедии								& quote

a_search	поиск													# что нужно найти?
a_search	найди _дзен _буддизм в википедии						& quote

a_search	поиск													# что нужно найти?
a_search	что такое _дзен _буддизм в википедии					& quote

a_search	поиск													# что нужно найти?
a_search	найди что такое _дзен _буддизм в википедии				& quote


# with source + 2 search-words

a_search	поиск													# что нужно найти?
a_search	википедия _дзен _буддизм								& quote

a_search	поиск													# что нужно найти?
a_search	найди в википедии _дзен _буддизм						& quote

a_search	поиск													# что нужно найти?
a_search	найди в википедии статью про _дзен _буддизм				& quote



#####
# with 3 search-words + source

a_search	поиск													# что нужно найти?
a_search	_основы _дзен _буддизма									& quote

a_search	поиск													# что нужно найти?
a_search	найди _основы _дзен _буддизма							& quote

a_search	поиск													# что нужно найти?
a_search	что такое _основы _дзен _буддизма						& quote

a_search	поиск													# что нужно найти?
a_search	найди что такое _основы _дзен _буддизма					& quote


# with 3 search-words + source

a_search	поиск													# что нужно найти?
a_search	_основы _дзен _буддизма в википедии						& quote

a_search	поиск													# что нужно найти?
a_search	найди _основы _дзен _буддизма в википедии				& quote

a_search	поиск													# что нужно найти?
a_search	что такое _основы _дзен _буддизма в википедии			& quote

a_search	поиск													# что нужно найти?
a_search	найди что такое _основы _дзен _буддизма в википедии		& quote


# with source + 3 search-words

a_search	поиск													# что нужно найти?
a_search	википедия _основы _дзен _буддизма						& quote

a_search	поиск													# что нужно найти?
a_search	найди в википедии _основы _дзен _буддизма				& quote

a_search	поиск													# что нужно найти?
a_search	найди в википедии статью про _основы _дзен _буддизма


#####
# complicated text (action keywords included)					& quote

a_search	поиск													# что нужно найти?
a_search	_как _позвонить _в _австралию							& quote

a_search	поиск													# что нужно найти?
a_search	_как _писать _смс _сообщения							& quote

a_search	поиск													# что нужно найти?
a_search	_как _писать _электронные _письма						& quote

a_search	поиск													# что нужно найти?
a_search	_как _искать _в _интернете								& quote

a_search	поиск													# что нужно найти?
a_search	_как _открыть _сайт _в _браузере						& quote

a_search	поиск													# что нужно найти?
a_search	_как _поставить _будильник								& quote

a_search	поиск													# что нужно найти?
a_search	_как _проверить баланс									& quote


# complicated text (params keywords included)

a_search	поиск													# что нужно найти?
a_search	_как _позвонить _васе									& quote

a_search	поиск													# что нужно найти?
a_search	_как _написать _смс _с _текстом _привет					& quote

a_search	поиск													# что нужно найти?
a_search	_как _написать _письмо _с _текстом _привет				& quote

a_search	поиск													# что нужно найти?
a_search	_как _найти _в _интернете _что _такое _дзен				& quote

a_search	поиск													# что нужно найти?
a_search	_как _открыть _yandex.ru _в _браузере					& quote

a_search	поиск													# что нужно найти?
a_search	_как _поставить _будильник _на _7 _утра					& quote


# complicated text: action keywords included + a_search					& quote

a_search	поиск													# что нужно найти?
a_search	найди _как _позвонить _в _австралию						& quote

a_search	поиск													# что нужно найти?
a_search	найди _как _писать _смс _сообщения						& quote

a_search	поиск													# что нужно найти?
a_search	найди _как _писать _электронные _письма					& quote

a_search	поиск													# что нужно найти?
a_search	найди _как _искать _в _интернете						& quote

a_search	поиск													# что нужно найти?
a_search	найди _как _открыть _сайт _в _браузере					& quote

a_search	поиск													# что нужно найти?
a_search	найди _как _поставить _будильник						& quote

a_search	поиск													# что нужно найти?
a_search	найди _как _проверить баланс							& quote


# complicated text: params keywords included + a_search

a_search	поиск													# что нужно найти?
a_search	найди _как _позвонить _васе								& quote

a_search	поиск													# что нужно найти?
a_search	найди _как _написать _смс _с _текстом _привет			& quote

a_search	поиск													# что нужно найти?
a_search	найди _как _написать _письмо _с _текстом _привет		& quote

a_search	поиск													# что нужно найти?
a_search	найди _как _найти _в _интернете _что _такое _дзен		& quote

a_search	поиск													# что нужно найти?
a_search	найди _как _открыть _yandex.ru _в _браузере				& quote

a_search	поиск													# что нужно найти?
a_search	найди _как _поставить _будильник _на _7 _утра			& quote


#####
# cancellation, 1 s_change word

a_search	поиск													# что нужно найти?
a_call	нет позвони васе											& quote

a_search	поиск													# что нужно найти?
a_sms	нет напиши смс												& quote

a_search	поиск													# что нужно найти?
a_email	нет напиши письмо											& quote

a_search	поиск													# что нужно найти?
a_search	нет найди мне статью									& quote

a_search	поиск													# что нужно найти?
a_site	нет открой мне сайт											& quote

a_search	поиск													# что нужно найти?
a_alarm	нет поставь будильник										& quote

a_search	поиск													# что нужно найти?
a_balance	нет покажи баланс										& quote

a_search	поиск													# что нужно найти?
a_cancel	отмена													& quote


# cancellation, 2 s_change words

a_search	поиск													# что нужно найти?
a_call	хотя нет позвони васе										& quote

a_search	поиск													# что нужно найти?
a_sms	хотя нет напиши смс											& quote

a_search	поиск													# что нужно найти?
a_email	хотя нет напиши письмо										& quote

a_search	поиск													# что нужно найти?
a_search	хотя нет найди мне статью								& quote

a_search	поиск													# что нужно найти?
a_site	хотя нет открой мне сайт									& quote

a_search	поиск													# что нужно найти?
a_alarm	хотя нет поставь будильник									& quote

a_search	поиск													# что нужно найти?
a_balance	хотя нет покажи баланс									& quote


# cancellation, 3 s_change words

a_search	поиск													# что нужно найти?
a_call	хотя нет лучше позвони васе									& quote

a_search	поиск													# что нужно найти?
a_sms	хотя нет лучше напиши смс									& quote

a_search	поиск													# что нужно найти?
a_email	хотя нет лучше напиши письмо								& quote

a_search	поиск													# что нужно найти?
a_search	хотя нет лучше найди мне статью							& quote

a_search	поиск													# что нужно найти?
a_site	хотя нет лучше открой мне сайт								& quote

a_search	поиск													# что нужно найти?
a_alarm	хотя нет лучше поставь будильник							& quote

a_search	поиск													# что нужно найти?
a_balance	хотя нет лучше покажи баланс							& quote





# A_SITE section #######################################################
# 1 word

a_site	сайт								# какой сайт открыть?
a_site	msu.ru								& p_site

a_site	сайт								# какой сайт открыть?
a_site	сайт msu.ru							& p_site

a_site	сайт								# какой сайт открыть?
a_site	покажи msu.ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой msu.ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой в браузере msu.ru			& p_site

a_site	сайт								# какой сайт открыть?
a_site	покажи сайт msu.ru					& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой сайт msu.ru					& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой в браузере сайт msu.ru		& p_site


# 2 words			& p_site

a_site	сайт								# какой сайт открыть?
a_site	msu ru								& p_site

a_site	сайт								# какой сайт открыть?
a_site	сайт msu ru							& p_site

a_site	сайт								# какой сайт открыть?
a_site	покажи msu ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой msu ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой в браузере msu ru			& p_site

a_site	сайт								# какой сайт открыть?
a_site	покажи сайт msu ru					& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой сайт msu ru					& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой в браузере сайт msu ru		& p_site


# 3 words			& p_site

a_site	сайт								# какой сайт открыть?
a_site	msu . ru							& p_site

a_site	сайт								# какой сайт открыть?
a_site	сайт msu . ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	покажи msu . ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой msu . ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой в браузере msu . ru			& p_site

a_site	сайт								# какой сайт открыть?
a_site	покажи сайт msu . ru				& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой сайт msu . ru				& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой в браузере сайт msu . ru		& p_site


#####
# cancellation, 1 s_change word

a_site	сайт								# какой сайт открыть?
a_call	нет позвони васе					& p_site

a_site	сайт								# какой сайт открыть?
a_sms	нет напиши смс						& p_site

a_site	сайт								# какой сайт открыть?
a_email	нет напиши письмо					& p_site

a_site	сайт								# какой сайт открыть?
a_search	нет найди мне статью			& p_site

a_site	сайт								# какой сайт открыть?
a_site	нет открой мне сайт					& p_site

a_site	сайт								# какой сайт открыть?
a_alarm	нет поставь будильник				& p_site

a_site	сайт								# какой сайт открыть?
a_balance	нет покажи баланс				& p_site

a_site	сайт								# какой сайт открыть?
a_cancel	отмена							& p_site


# cancellation, 2 s_change words

a_site	сайт								# какой сайт открыть?
a_call	хотя нет позвони васе				& p_site

a_site	сайт								# какой сайт открыть?
a_sms	хотя нет напиши смс					& p_site

a_site	сайт								# какой сайт открыть?
a_email	хотя нет напиши письмо				& p_site

a_site	сайт								# какой сайт открыть?
a_search	хотя нет найди мне статью		& p_site

a_site	сайт								# какой сайт открыть?
a_site	хотя нет открой мне сайт			& p_site

a_site	сайт								# какой сайт открыть?
a_alarm	хотя нет поставь будильник			& p_site

a_site	сайт								# какой сайт открыть?
a_balance	хотя нет покажи баланс			& p_site


# cancellation, 3 s_change words			& p_site

a_site	сайт								# какой сайт открыть?
a_call	хотя нет лучше позвони васе			& p_site

a_site	сайт								# какой сайт открыть?
a_sms	хотя нет лучше напиши смс			& p_site

a_site	сайт								# какой сайт открыть?
a_email	хотя нет лучше напиши письмо		& p_site

a_site	сайт								# какой сайт открыть?
a_search	хотя нет лучше найди мне статью	& p_site

a_site	сайт								# какой сайт открыть?
a_site	хотя нет лучше открой мне сайт		& p_site

a_site	сайт								# какой сайт открыть?
a_alarm	хотя нет лучше поставь будильник	& p_site

a_site	сайт								# какой сайт открыть?
a_balance	хотя нет лучше покажи баланс	& p_site





# A_ALARM section ######################################################
# numbers

a_alarm	будильник 													# на какое время?
a_alarm	Time:7														& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:7 Time:30												& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:7 часов												& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:7 часов утра											& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:7 часов Time:30 минут									& p_time


a_alarm	будильник 													# на какое время?
a_alarm	на Time:7													& p_time

a_alarm	будильник 													# на какое время?
a_alarm	на Time:7 Time:30											& p_time

a_alarm	будильник 													# на какое время?
a_alarm	на Time:7 часов Time:30 минут								& p_time


a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:7											& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:7 Time:30									& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:7 часов Time:30 минут						& p_time


a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:7									& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:7 Time:30							& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:7 часов Time:30 минут				& p_time



# 1 txtnums

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь													& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь Time:30											& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь часов												& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь часов утра										& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь часов Time:30 минут								& p_time


a_alarm	будильник 													# на какое время?
a_alarm	на Time:семь												& p_time

a_alarm	будильник 													# на какое время?
a_alarm	на Time:семь Time:30										& p_time

a_alarm	будильник 													# на какое время?
a_alarm	на Time:семь часов Time:30 минут							& p_time


a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:семь										& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:семь Time:30								& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:семь часов Time:30 минут					& p_time


a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:семь								& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:семь Time:30						& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:семь часов Time:30 минут			& p_time


# 2 txtnums

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь													& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь Time:тридцать										& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь часов												& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь часов утра										& p_time

a_alarm	будильник 													# на какое время?
a_alarm	Time:семь часов Time:тридцать минут							& p_time


a_alarm	будильник 													# на какое время?
a_alarm	на Time:семь												& p_time

a_alarm	будильник 													# на какое время?
a_alarm	на Time:семь Time:тридцать									& p_time

a_alarm	будильник 													# на какое время?
a_alarm	на Time:семь часов Time:тридцать минут						& p_time


a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:семь										& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:семь Time:тридцать							& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь на Time:семь часов Time:тридцать минут				& p_time


a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:семь								& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:семь Time:тридцать				& p_time

a_alarm	будильник 													# на какое время?
a_alarm	поставь будильник на Time:семь часов Time:тридцать минут	& p_time


# cancellation, 1 s_change word

a_alarm	будильник 													# на какое время?
a_call	нет позвони васе											& p_time

a_alarm	будильник 													# на какое время?
a_sms	нет напиши смс												& p_time

a_alarm	будильник 													# на какое время?
a_email	нет напиши письмо											& p_time

a_alarm	будильник 													# на какое время?
a_search	нет найди мне статью									& p_time

a_alarm	будильник 													# на какое время?
a_site	нет открой мне сайт											& p_time

a_alarm	будильник 													# на какое время?
a_alarm	нет поставь будильник										& p_time

a_alarm	будильник 													# на какое время?
a_balance	нет покажи баланс										& p_time

a_alarm	будильник 													# на какое время?
a_cancel	отмена													& p_time


# cancellation, 2 s_change words

a_alarm	будильник 													# на какое время?
a_call	хотя нет позвони васе										& p_time

a_alarm	будильник 													# на какое время?
a_sms	хотя нет напиши смс											& p_time

a_alarm	будильник 													# на какое время?
a_email	хотя нет напиши письмо										& p_time

a_alarm	будильник 													# на какое время?
a_search	хотя нет найди мне статью								& p_time

a_alarm	будильник 													# на какое время?
a_site	хотя нет открой мне сайт									& p_time

a_alarm	будильник 													# на какое время?
a_alarm	хотя нет поставь будильник									& p_time

a_alarm	будильник 													# на какое время?
a_balance	хотя нет покажи баланс									& p_time


# cancellation, 3 s_change words

a_alarm	будильник 													# на какое время?
a_cancel	отмена													& p_time

a_alarm	будильник 													# на какое время?
a_call	хотя нет лучше позвони васе									& p_time

a_alarm	будильник 													# на какое время?
a_sms	хотя нет лучше напиши смс									& p_time

a_alarm	будильник 													# на какое время?
a_email	хотя нет лучше напиши письмо								& p_time

a_alarm	будильник 													# на какое время?
a_search	хотя нет лучше найди мне статью							& p_time

a_alarm	будильник 													# на какое время?
a_site	хотя нет лучше открой мне сайт								& p_time

a_alarm	будильник 													# на какое время?
a_alarm	хотя нет лучше поставь будильник							& p_time

a_alarm	будильник 													# на какое время?
a_balance	хотя нет лучше покажи баланс							& p_time



