#!/bin/bash #this line is for highlighting purpose only
# A_SITE section #######################################################
# 1 word

a_site	yandex.ru
a_site	открой yandex.ru

a_site	пожалуйста открой yandex.ru
a_site	открой пожалуйста yandex.ru
a_site	открой yandex.ru пожалуйста

a_site	пожалуйста открой мне yandex.ru
a_site	открой мне пожалуйста yandex.ru
a_site	открой пожалуйста мне yandex.ru
a_site	открой мне yandex.ru пожалуйста

a_site	открой в браузере yandex.ru
a_site	открой yandex.ru в браузере

a_site	пожалуйста открой в браузере yandex.ru
a_site	открой пожалуйста в браузере yandex.ru
a_site	открой в браузере yandex.ru пожалуйста

a_site	пожалуйста открой yandex.ru в браузере
a_site	открой пожалуйста yandex.ru в браузере
a_site	открой yandex.ru в браузере пожалуйста


# 2 words

a_site	google com
a_site	открой google com

a_site	пожалуйста открой google com
a_site	открой пожалуйста google com
a_site	открой google com пожалуйста

a_site	пожалуйста открой мне google com
a_site	открой мне пожалуйста google com
a_site	открой пожалуйста мне google com
a_site	открой мне google com пожалуйста

a_site	открой в браузере google com
a_site	открой google com в браузере

a_site	пожалуйста открой в браузере google com
a_site	открой пожалуйста в браузере google com
a_site	открой в браузере google com пожалуйста

a_site	пожалуйста открой google com в браузере
a_site	открой пожалуйста google com в браузере
a_site	открой google com в браузере пожалуйста


# 3 words

a_site	википедия точка орг
a_site	открой википедия точка орг

a_site	пожалуйста открой википедия точка орг
a_site	открой пожалуйста википедия точка орг
a_site	открой википедия точка орг пожалуйста

a_site	пожалуйста открой мне википедия точка орг
a_site	открой мне пожалуйста википедия точка орг
a_site	открой пожалуйста мне википедия точка орг
a_site	открой мне википедия точка орг пожалуйста

a_site	открой в браузере википедия точка орг
a_site	открой википедия точка орг в браузере

a_site	пожалуйста открой в браузере википедия точка орг
a_site	открой пожалуйста в браузере википедия точка орг
a_site	открой в браузере википедия точка орг пожалуйста

a_site	пожалуйста открой википедия точка орг в браузере
a_site	открой пожалуйста википедия точка орг в браузере
a_site	открой википедия точка орг в браузере пожалуйста
