#!/bin/bash #this line is for highlighting purpose only
# A_CANCEL section #####################################################
a_cancel	отмена
a_cancel	ладно неважно
a_cancel	неважно уже
a_cancel	забей на это
a_cancel	ладно забей на это
