#!/bin/bash #this line is for highlighting purpose only
# A_SEARCH section #####################################################

# with 1 search-word					& quote

a_search	поиск													# что нужно найти?
a_search	QUOTE:дзен													& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:дзен												& quote

a_search	поиск													# что нужно найти?
a_search	что такое QUOTE:дзен											& quote

a_search	поиск													# что нужно найти?
a_search	найди что такое QUOTE:дзен									& quote


# with 1 search-word + source

a_search	поиск													# что нужно найти?
a_search	QUOTE:дзен в википедии										& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:дзен в википедии									& quote

a_search	поиск													# что нужно найти?
a_search	что такое QUOTE:дзен в википедии								& quote

a_search	поиск													# что нужно найти?
a_search	найди что такое QUOTE:дзен в википедии						& quote


# with source + 1 search-word

a_search	поиск													# что нужно найти?
a_search	википедия QUOTE:дзен											& quote

a_search	поиск													# что нужно найти?
a_search	найди в википедии QUOTE:дзен									& quote

a_search	поиск													# что нужно найти?
a_search	найди в википедии статью про QUOTE:дзен						& quote


#####
# with 2 search-words + source

a_search	поиск													# что нужно найти?
a_search	QUOTE:дзен QUOTE:буддизм											& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:дзен QUOTE:буддизм									& quote

a_search	поиск													# что нужно найти?
a_search	что такое QUOTE:дзен QUOTE:буддизм								& quote

a_search	поиск													# что нужно найти?
a_search	найди что такое QUOTE:дзен QUOTE:буддизм							& quote


# with 2 search-words + source

a_search	поиск													# что нужно найти?
a_search	QUOTE:дзен QUOTE:буддизм в википедии								& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:дзен QUOTE:буддизм в википедии						& quote

a_search	поиск													# что нужно найти?
a_search	что такое QUOTE:дзен QUOTE:буддизм в википедии					& quote

a_search	поиск													# что нужно найти?
a_search	найди что такое QUOTE:дзен QUOTE:буддизм в википедии				& quote


# with source + 2 search-words

a_search	поиск													# что нужно найти?
a_search	википедия QUOTE:дзен QUOTE:буддизм								& quote

a_search	поиск													# что нужно найти?
a_search	найди в википедии QUOTE:дзен QUOTE:буддизм						& quote

a_search	поиск													# что нужно найти?
a_search	найди в википедии статью про QUOTE:дзен QUOTE:буддизм				& quote



#####
# with 3 search-words + source

a_search	поиск													# что нужно найти?
a_search	QUOTE:основы QUOTE:дзен QUOTE:буддизма									& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:основы QUOTE:дзен QUOTE:буддизма							& quote

a_search	поиск													# что нужно найти?
a_search	что такое QUOTE:основы QUOTE:дзен QUOTE:буддизма						& quote

a_search	поиск													# что нужно найти?
a_search	найди что такое QUOTE:основы QUOTE:дзен QUOTE:буддизма					& quote


# with 3 search-words + source

a_search	поиск													# что нужно найти?
a_search	QUOTE:основы QUOTE:дзен QUOTE:буддизма в википедии						& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:основы QUOTE:дзен QUOTE:буддизма в википедии				& quote

a_search	поиск													# что нужно найти?
a_search	что такое QUOTE:основы QUOTE:дзен QUOTE:буддизма в википедии			& quote

a_search	поиск													# что нужно найти?
a_search	найди что такое QUOTE:основы QUOTE:дзен QUOTE:буддизма в википедии		& quote


# with source + 3 search-words

a_search	поиск													# что нужно найти?
a_search	википедия QUOTE:основы QUOTE:дзен QUOTE:буддизма						& quote

a_search	поиск													# что нужно найти?
a_search	найди в википедии QUOTE:основы QUOTE:дзен QUOTE:буддизма				& quote

a_search	поиск													# что нужно найти?
a_search	найди в википедии статью про QUOTE:основы QUOTE:дзен QUOTE:буддизма


#####
# complicated text (action keywords included)					& quote

a_search	поиск													# что нужно найти?
a_search	QUOTE:как QUOTE:позвонить QUOTE:в QUOTE:австралию							& quote

a_search	поиск													# что нужно найти?
a_search	QUOTE:как QUOTE:писать QUOTE:смс QUOTE:сообщения							& quote

a_search	поиск													# что нужно найти?
a_search	QUOTE:как QUOTE:писать QUOTE:электронные QUOTE:письма						& quote

a_search	поиск													# что нужно найти?
a_search	QUOTE:как QUOTE:искать QUOTE:в QUOTE:интернете								& quote

a_search	поиск													# что нужно найти?
a_search	QUOTE:как QUOTE:открыть QUOTE:сайт QUOTE:в QUOTE:браузере						& quote

a_search	поиск													# что нужно найти?
a_search	QUOTE:как QUOTE:поставить QUOTE:будильник								& quote

a_search	поиск													# что нужно найти?
a_search	QUOTE:как QUOTE:проверить баланс									& quote


# complicated text (params keywords included)

a_search	поиск													# что нужно найти?
a_search	QUOTE:как QUOTE:позвонить QUOTE:васе									& quote

a_search	поиск													# что нужно найти?
a_search	QUOTE:как QUOTE:написать QUOTE:смс QUOTE:с QUOTE:текстом QUOTE:привет					& quote

a_search	поиск													# что нужно найти?
a_search	QUOTE:как QUOTE:написать QUOTE:письмо QUOTE:с QUOTE:текстом QUOTE:привет				& quote

a_search	поиск													# что нужно найти?
a_search	QUOTE:как QUOTE:найти QUOTE:в QUOTE:интернете QUOTE:что QUOTE:такое QUOTE:дзен				& quote

a_search	поиск													# что нужно найти?
a_search	QUOTE:как QUOTE:открыть QUOTE:yandex.ru QUOTE:в QUOTE:браузере					& quote

a_search	поиск													# что нужно найти?
a_search	QUOTE:как QUOTE:поставить QUOTE:будильник QUOTE:на QUOTE:7 QUOTE:утра					& quote


# complicated text: action keywords included + a_search					& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:как QUOTE:позвонить QUOTE:в QUOTE:австралию						& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:как QUOTE:писать QUOTE:смс QUOTE:сообщения						& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:как QUOTE:писать QUOTE:электронные QUOTE:письма					& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:как QUOTE:искать QUOTE:в QUOTE:интернете						& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:как QUOTE:открыть QUOTE:сайт QUOTE:в QUOTE:браузере					& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:как QUOTE:поставить QUOTE:будильник						& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:как QUOTE:проверить баланс							& quote


# complicated text: params keywords included + a_search

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:как QUOTE:позвонить QUOTE:васе								& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:как QUOTE:написать QUOTE:смс QUOTE:с QUOTE:текстом QUOTE:привет			& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:как QUOTE:написать QUOTE:письмо QUOTE:с QUOTE:текстом QUOTE:привет		& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:как QUOTE:найти QUOTE:в QUOTE:интернете QUOTE:что QUOTE:такое QUOTE:дзен		& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:как QUOTE:открыть QUOTE:yandex.ru QUOTE:в QUOTE:браузере				& quote

a_search	поиск													# что нужно найти?
a_search	найди QUOTE:как QUOTE:поставить QUOTE:будильник QUOTE:на QUOTE:7 QUOTE:утра			& quote


#####
# cancellation, 1 s_change word

a_search	поиск													# что нужно найти?
a_call	нет позвони васе											& quote

a_search	поиск													# что нужно найти?
a_sms	нет напиши смс												& quote

a_search	поиск													# что нужно найти?
a_email	нет напиши письмо											& quote

a_search	поиск													# что нужно найти?
a_search	нет найди мне статью									& quote

a_search	поиск													# что нужно найти?
a_site	нет открой мне сайт											& quote

a_search	поиск													# что нужно найти?
a_alarm	нет поставь будильник										& quote

a_search	поиск													# что нужно найти?
a_balance	нет покажи баланс										& quote

a_search	поиск													# что нужно найти?
a_cancel	отмена													& quote


# cancellation, 2 s_change words

a_search	поиск													# что нужно найти?
a_call	хотя нет позвони васе										& quote

a_search	поиск													# что нужно найти?
a_sms	хотя нет напиши смс											& quote

a_search	поиск													# что нужно найти?
a_email	хотя нет напиши письмо										& quote

a_search	поиск													# что нужно найти?
a_search	хотя нет найди мне статью								& quote

a_search	поиск													# что нужно найти?
a_site	хотя нет открой мне сайт									& quote

a_search	поиск													# что нужно найти?
a_alarm	хотя нет поставь будильник									& quote

a_search	поиск													# что нужно найти?
a_balance	хотя нет покажи баланс									& quote


# cancellation, 3 s_change words

a_search	поиск													# что нужно найти?
a_call	хотя нет лучше позвони васе									& quote

a_search	поиск													# что нужно найти?
a_sms	хотя нет лучше напиши смс									& quote

a_search	поиск													# что нужно найти?
a_email	хотя нет лучше напиши письмо								& quote

a_search	поиск													# что нужно найти?
a_search	хотя нет лучше найди мне статью							& quote

a_search	поиск													# что нужно найти?
a_site	хотя нет лучше открой мне сайт								& quote

a_search	поиск													# что нужно найти?
a_alarm	хотя нет лучше поставь будильник							& quote

a_search	поиск													# что нужно найти?
a_balance	хотя нет лучше покажи баланс							& quote



