#!/bin/bash #this line is for highlighting purpose only
# A_SITE section #######################################################
# 1 word

a_site	сайт								# какой сайт открыть?
a_site	P_SITE:msu.ru								& p_site

a_site	сайт								# какой сайт открыть?
a_site	сайт P_SITE:msu.ru							& p_site

a_site	сайт								# какой сайт открыть?
a_site	покажи P_SITE:msu.ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой P_SITE:msu.ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой в браузере P_SITE:msu.ru			& p_site

a_site	сайт								# какой сайт открыть?
a_site	покажи сайт P_SITE:msu.ru					& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой сайт P_SITE:msu.ru					& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой в браузере сайт P_SITE:msu.ru		& p_site


# 2 words

a_site	сайт								# какой сайт открыть?
a_site	P_SITE:msu P_SITE:ru								& p_site

a_site	сайт								# какой сайт открыть?
a_site	сайт P_SITE:msu P_SITE:ru							& p_site

a_site	сайт								# какой сайт открыть?
a_site	покажи P_SITE:msu P_SITE:ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой P_SITE:msu P_SITE:ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой в браузере P_SITE:msu P_SITE:ru			& p_site

a_site	сайт								# какой сайт открыть?
a_site	покажи сайт P_SITE:msu P_SITE:ru					& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой сайт P_SITE:msu P_SITE:ru					& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой в браузере сайт P_SITE:msu P_SITE:ru		& p_site


# 3 words

a_site	сайт								# какой сайт открыть?
a_site	P_SITE:msu P_SITE:. P_SITE:ru							& p_site

a_site	сайт								# какой сайт открыть?
a_site	сайт P_SITE:msu P_SITE:. P_SITE:ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	покажи P_SITE:msu P_SITE:. P_SITE:ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой P_SITE:msu P_SITE:. P_SITE:ru						& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой в браузере P_SITE:msu P_SITE:. P_SITE:ru			& p_site

a_site	сайт								# какой сайт открыть?
a_site	покажи сайт P_SITE:msu P_SITE:. P_SITE:ru				& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой сайт P_SITE:msu P_SITE:. P_SITE:ru				& p_site

a_site	сайт								# какой сайт открыть?
a_site	открой в браузере сайт P_SITE:msu P_SITE:. P_SITE:ru		& p_site


#####
# cancellation, 1 s_change word

a_site	сайт								# какой сайт открыть?
a_call	нет позвони васе					& p_site

a_site	сайт								# какой сайт открыть?
a_sms	нет напиши смс						& p_site

a_site	сайт								# какой сайт открыть?
a_email	нет напиши письмо					& p_site

a_site	сайт								# какой сайт открыть?
a_search	нет найди мне статью			& p_site

a_site	сайт								# какой сайт открыть?
a_site	нет открой мне сайт					& p_site

a_site	сайт								# какой сайт открыть?
a_alarm	нет поставь будильник				& p_site

a_site	сайт								# какой сайт открыть?
a_balance	нет покажи баланс				& p_site

a_site	сайт								# какой сайт открыть?
a_cancel	отмена							& p_site


# cancellation, 2 s_change words

a_site	сайт								# какой сайт открыть?
a_call	хотя нет позвони васе				& p_site

a_site	сайт								# какой сайт открыть?
a_sms	хотя нет напиши смс					& p_site

a_site	сайт								# какой сайт открыть?
a_email	хотя нет напиши письмо				& p_site

a_site	сайт								# какой сайт открыть?
a_search	хотя нет найди мне статью		& p_site

a_site	сайт								# какой сайт открыть?
a_site	хотя нет открой мне сайт			& p_site

a_site	сайт								# какой сайт открыть?
a_alarm	хотя нет поставь будильник			& p_site

a_site	сайт								# какой сайт открыть?
a_balance	хотя нет покажи баланс			& p_site


# cancellation, 3 s_change words

a_site	сайт								# какой сайт открыть?
a_call	хотя нет лучше позвони васе			& p_site

a_site	сайт								# какой сайт открыть?
a_sms	хотя нет лучше напиши смс			& p_site

a_site	сайт								# какой сайт открыть?
a_email	хотя нет лучше напиши письмо		& p_site

a_site	сайт								# какой сайт открыть?
a_search	хотя нет лучше найди мне статью	& p_site

a_site	сайт								# какой сайт открыть?
a_site	хотя нет лучше открой мне сайт		& p_site

a_site	сайт								# какой сайт открыть?
a_alarm	хотя нет лучше поставь будильник	& p_site

a_site	сайт								# какой сайт открыть?
a_balance	хотя нет лучше покажи баланс	& p_site


