#!/bin/bash #this line is for highlighting purpose only
# A_SMS section ########################################################

# with text
a_sms	смс													# что написать?
a_sms	QUOTE:привет												& quote

a_sms	смс													# что написать?
a_sms	QUOTE:привет QUOTE:вася										& quote

a_sms	смс													# что написать?
a_sms	QUOTE:привет QUOTE:как QUOTE:дела									& quote

a_sms	смс													# что написать?
a_sms	QUOTE:привет QUOTE:вася QUOTE:как QUOTE:дела							& quote


# with ambiguous "напиши" and text

a_sms	смс													# что написать?
a_sms	напиши QUOTE:привет										& quote

a_sms	смс													# что написать?
a_sms	напиши QUOTE:привет QUOTE:вася								& quote

a_sms	смс													# что написать?
a_sms	напиши QUOTE:привет QUOTE:как QUOTE:дела							& quote

a_sms	смс													# что написать?
a_sms	напиши QUOTE:привет QUOTE:вася QUOTE:как QUOTE:дела						& quote


# with s_text and text

a_sms	смс													# что написать?
a_sms	с текстом QUOTE:привет									& quote

a_sms	смс													# что написать?
a_sms	с текстом QUOTE:привет QUOTE:вася								& quote

a_sms	смс													# что написать?
a_sms	с текстом QUOTE:привет QUOTE:как QUOTE:дела						& quote

a_sms	смс													# что написать?
a_sms	с текстом QUOTE:привет QUOTE:вася QUOTE:как QUOTE:дела					& quote


# with name

a_sms	смс													# кому?
a_sms	васе												& p_name

a_sms	смс													# кому?
a_sms	васе петрову										& p_name

a_sms	смс													# кому?
a_sms	василию ивановичу петрову							& p_name


# with a_sms + name

a_sms	смс													# кому?
a_sms	смс васе											& p_name

a_sms	смс													# кому?
a_sms	смс васе петрову									& p_name

a_sms	смс													# кому?
a_sms	смс василию ивановичу петрову						& p_name


# with ambiguous "отправь" + name

a_sms	смс													# кому?
a_sms	отправь васе										& p_name

a_sms	смс													# кому?
a_sms	отправь васе петрову								& p_name

a_sms	смс													# кому?
a_sms	отправь василию ивановичу петрову					& p_name


# with ambiguous "отправь" + a_sms and name

a_sms	смс													# кому?
a_sms	отправь смс васе									& p_name

a_sms	смс													# кому?
a_sms	отправь смс васе петрову							& p_name

a_sms	смс													# кому?
a_sms	отправь смс василию ивановичу петрову				& p_name


# with full command

a_sms	смс													# кому?
a_sms	смс васе с текстом QUOTE:привет							& p_name

a_sms	смс													# кому?
a_sms	смс василию ивановичу с текстом QUOTE:привет				& p_name

a_sms	смс													# кому?
a_sms	смс василию ивановичу петрову с текстом QUOTE:привет		& p_name

#####
# complicated text (action keywords included)

a_sms	смс													# что написать?
a_sms	QUOTE:почему QUOTE:не QUOTE:звонишь								& quote

a_sms	смс													# что написать?
a_sms	QUOTE:отправь QUOTE:сообщение QUOTE:васе							& quote

a_sms	смс													# что написать?
a_sms	QUOTE:получил QUOTE:твое QUOTE:письмо								& quote

a_sms	смс													# что написать?
a_sms	QUOTE:разбуди QUOTE:меня QUOTE:завтра QUOTE:в QUOTE:7						& quote

a_sms	смс													# что написать?
a_sms	QUOTE:открой QUOTE:браузер									& quote

a_sms	смс													# что написать?
a_sms	QUOTE:пополни QUOTE:мой QUOTE:баланс								& quote

a_sms	смс													# что написать?
a_sms	QUOTE:проверь QUOTE:баланс									& quote


# complicated text (params keywords included)

a_sms	смс													# что написать?
a_sms	QUOTE:привет QUOTE:от QUOTE:саши									& quote

a_sms	смс													# что написать?
a_sms	QUOTE:позвони QUOTE:на QUOTE:номер QUOTE:8 QUOTE:917 QUOTE:123 QUOTE:45 QUOTE:67			& quote

a_sms	смс													# что написать?
a_sms	QUOTE:sasha QUOTE:собака QUOTE:gmail.com							& quote

a_sms	смс													# что написать?
a_sms	QUOTE:зайди QUOTE:на QUOTE:yandex.ru								& quote

a_sms	смс													# что написать?
a_sms	QUOTE:завтра QUOTE:буду QUOTE:в QUOTE:7 QUOTE:часов							& quote

#####
# complicated text: action keywords included + a_sms

a_sms	смс													# что написать?
a_sms	напиши QUOTE:почему QUOTE:не QUOTE:звонишь							& quote

a_sms	смс													# что написать?
a_sms	напиши QUOTE:напиши QUOTE:мне									& quote

a_sms	смс													# что написать?
a_sms	напиши QUOTE:получил QUOTE:твое QUOTE:письмо						& quote

a_sms	смс													# что написать?
a_sms	напиши QUOTE:разбуди QUOTE:меня QUOTE:завтра QUOTE:в QUOTE:7					& quote

a_sms	смс													# что написать?
a_sms	напиши QUOTE:открой QUOTE:браузер								& quote

a_sms	смс													# что написать?
a_sms	напиши QUOTE:пополни QUOTE:мой QUOTE:баланс						& quote

a_sms	смс													# что написать?
a_sms	напиши QUOTE:проверь QUOTE:баланс								& quote


# complicated text: params keywords included + s_text

a_sms	смс													# что написать?
a_sms	напиши QUOTE:привет QUOTE:от QUOTE:саши							& quote

a_sms	смс													# что написать?
a_sms	напиши QUOTE:позвони QUOTE:на QUOTE:номер QUOTE:8 QUOTE:917 QUOTE:123 QUOTE:45 QUOTE:67		& quote

a_sms	смс													# что написать?
a_sms	напиши QUOTE:sasha QUOTE:собака QUOTE:gmail.com					& quote

a_sms	смс													# что написать?
a_sms	напиши QUOTE:зайди QUOTE:на QUOTE:yandex.ru						& quote

a_sms	смс													# что написать?
a_sms	напиши QUOTE:завтра QUOTE:буду QUOTE:в QUOTE:7 QUOTE:часов					& quote


# cancellation, 1 s_change word

a_sms	смс													# что написать?
a_call	нет позвони васе									& quote

a_sms	смс													# что написать?
a_sms	нет напиши смс										& quote

a_sms	смс													# что написать?
a_email	нет напиши письмо									& quote

a_sms	смс													# что написать?
a_search	нет найди мне статью							& quote

a_sms	смс													# что написать?
a_site	нет открой мне сайт									& quote

a_sms	смс													# что написать?
a_alarm	нет поставь будильник								& quote

a_sms	смс													# что написать?
a_balance	нет покажи баланс								& quote

a_sms	смс													# что написать?
a_cancel	отмена											& quote


# cancellation, 2 s_change words

a_sms	смс													# что написать?
a_call	хотя нет позвони васе								& quote

a_sms	смс													# что написать?
a_sms	хотя нет напиши смс									& quote

a_sms	смс													# что написать?
a_email	хотя нет напиши письмо								& quote

a_sms	смс													# что написать?
a_search	хотя нет найди мне статью						& quote

a_sms	смс													# что написать?
a_site	хотя нет открой мне сайт							& quote

a_sms	смс													# что написать?
a_alarm	хотя нет поставь будильник							& quote

a_sms	смс													# что написать?
a_balance	хотя нет покажи баланс							& quote


# cancellation, 3 s_change words

a_sms	смс													# что написать?
a_call	хотя нет лучше позвони васе							& quote

a_sms	смс													# что написать?
a_sms	хотя нет лучше напиши смс							& quote

a_sms	смс													# что написать?
a_email	хотя нет лучше напиши письмо						& quote

a_sms	смс													# что написать?
a_search	хотя нет лучше найди мне статью					& quote

a_sms	смс													# что написать?
a_site	хотя нет лучше открой мне сайт						& quote

a_sms	смс													# что написать?
a_alarm	хотя нет лучше поставь будильник					& quote

a_sms	смс													# что написать?
a_balance	хотя нет лучше покажи баланс					& quote
