#!/bin/bash #this line is for highlighting purpose only
# A_EMAIL section ######################################################

# with text
a_email	письмо												# что написать?
a_email	QUOTE:привет												& quote

a_email	письмо												# что написать?
a_email	QUOTE:привет QUOTE:вася										& quote

a_email	письмо												# что написать?
a_email	QUOTE:привет QUOTE:как QUOTE:дела									& quote

a_email	письмо												# что написать?
a_email	QUOTE:привет QUOTE:вася QUOTE:как QUOTE:дела


# with ambiguous "напиши" and text

a_email	письмо												# что написать?
a_email	напиши QUOTE:привет										& quote

a_email	письмо												# что написать?
a_email	напиши QUOTE:привет QUOTE:вася								& quote

a_email	письмо												# что написать?
a_email	напиши QUOTE:привет QUOTE:как QUOTE:дела							& quote

a_email	письмо												# что написать?
a_email	напиши QUOTE:привет QUOTE:вася QUOTE:как QUOTE:дела


# with s_text and text

a_email	письмо												# что написать?
a_email	с текстом QUOTE:привет									& quote

a_email	письмо												# что написать?
a_email	с текстом QUOTE:привет QUOTE:вася								& quote

a_email	письмо												# что написать?
a_email	с текстом QUOTE:привет QUOTE:как QUOTE:дела						& quote

a_email	письмо												# что написать?
a_email	с текстом QUOTE:привет QUOTE:вася QUOTE:как QUOTE:дела


# with name

a_email	письмо												# кому?
a_email	васе												& p_name

a_email	письмо												# кому?
a_email	васе петрову										& p_name

a_email	письмо												# кому?
a_email	василию ивановичу петрову							& p_name


# with a_email + name

a_email	письмо												# кому?
a_email	письмо васе											& p_name

a_email	письмо												# кому?
a_email	письмо васе петрову									& p_name

a_email	письмо												# кому?
a_email	письмо василию ивановичу петрову					& p_name


# with ambiguous "отправь" + name

a_email	письмо												# кому?
a_email	отправь васе										& p_name

a_email	письмо												# кому?
a_email	отправь васе петрову								& p_name

a_email	письмо												# кому?
a_email	отправь василию ивановичу петрову					& p_name


# with ambiguous "отправь" + a_email and name

a_email	письмо												# кому?
a_email	отправь письмо васе									& p_name

a_email	письмо												# кому?
a_email	отправь письмо васе петрову							& p_name

a_email	письмо												# кому?
a_email	отправь письмо василию ивановичу петрову			& p_name


# with full command

a_email	письмо												# кому?
a_email	письмо васе с текстом QUOTE:привет						& p_name

a_email	письмо												# кому?
a_email	письмо василию ивановичу с текстом QUOTE:привет			& p_name

a_email	письмо												# кому?
a_email	письмо василию ивановичу петрову с текстом QUOTE:привет	& p_name

#####
# complicated text (action keywords included)

a_email	письмо												# что написать?
a_email	QUOTE:почему QUOTE:не QUOTE:звонишь								& quote

a_email	письмо												# что написать?
a_email	QUOTE:отправь QUOTE:сообщение QUOTE:васе							& quote

a_email	письмо												# что написать?
a_email	QUOTE:получил QUOTE:твое QUOTE:письмо								& quote

a_email	письмо												# что написать?
a_email	QUOTE:разбуди QUOTE:меня QUOTE:завтра QUOTE:в QUOTE:7						& quote

a_email	письмо												# что написать?
a_email	QUOTE:открой QUOTE:браузер									& quote

a_email	письмо												# что написать?
a_email	QUOTE:пополни QUOTE:мой QUOTE:баланс								& quote

a_email	письмо												# что написать?
a_email	QUOTE:проверь QUOTE:баланс									& quote


# complicated text (params keywords included)

a_email	письмо												# что написать?
a_email	QUOTE:привет QUOTE:от QUOTE:саши									& quote

a_email	письмо												# что написать?
a_email	QUOTE:позвони QUOTE:на QUOTE:номер QUOTE:8 QUOTE:917 QUOTE:123 QUOTE:45 QUOTE:67			& quote

a_email	письмо												# что написать?
a_email	QUOTE:sasha QUOTE:собака QUOTE:gmail.com							& quote

a_email	письмо												# что написать?
a_email	QUOTE:зайди QUOTE:на QUOTE:yandex.ru								& quote

a_email	письмо												# что написать?
a_email	QUOTE:завтра QUOTE:буду QUOTE:в QUOTE:7 QUOTE:часов							& quote

#####
# complicated text: action keywords included + a_email

a_email	письмо												# что написать?
a_email	напиши QUOTE:почему QUOTE:не QUOTE:звонишь							& quote

a_email	письмо												# что написать?
a_email	напиши QUOTE:напиши QUOTE:мне									& quote

a_email	письмо												# что написать?
a_email	напиши QUOTE:получил QUOTE:твое QUOTE:письмо						& quote

a_email	письмо												# что написать?
a_email	напиши QUOTE:разбуди QUOTE:меня QUOTE:завтра QUOTE:в QUOTE:7					& quote

a_email	письмо												# что написать?
a_email	напиши QUOTE:открой QUOTE:браузер								& quote

a_email	письмо												# что написать?
a_email	напиши QUOTE:пополни QUOTE:мой QUOTE:баланс						& quote

a_email	письмо												# что написать?
a_email	напиши QUOTE:проверь QUOTE:баланс


# complicated text: params keywords included + s_text

a_email	письмо												# что написать?
a_email	напиши QUOTE:привет QUOTE:от QUOTE:саши							& quote

a_email	письмо												# что написать?
a_email	напиши QUOTE:позвони QUOTE:на QUOTE:номер QUOTE:8 QUOTE:917 QUOTE:123 QUOTE:45 QUOTE:67		& quote

a_email	письмо												# что написать?
a_email	напиши QUOTE:sasha QUOTE:собака QUOTE:gmail.com					& quote

a_email	письмо												# что написать?
a_email	напиши QUOTE:зайди QUOTE:на QUOTE:yandex.ru						& quote

a_email	письмо												# что написать?
a_email	напиши QUOTE:завтра QUOTE:буду QUOTE:в QUOTE:7 QUOTE:часов					& quote


# cancellation, 1 s_change word

a_email	письмо												# что написать?
a_call	нет позвони васе									& quote

a_email	письмо												# что написать?
a_sms	нет напиши смс										& quote

a_email	письмо												# что написать?
a_email	нет напиши письмо									& quote

a_email	письмо												# что написать?
a_search	нет найди мне статью							& quote

a_email	письмо												# что написать?
a_site	нет открой мне сайт									& quote

a_email	письмо												# что написать?
a_alarm	нет поставь будильник								& quote

a_email	письмо												# что написать?
a_balance	нет покажи баланс								& quote

a_email	письмо												# что написать?
a_cancel	отмена											& quote


# cancellation, 2 s_change words

a_email	письмо												# что написать?
a_call	хотя нет позвони васе								& quote

a_email	письмо												# что написать?
a_sms	хотя нет напиши смс									& quote

a_email	письмо												# что написать?
a_email	хотя нет напиши письмо								& quote

a_email	письмо												# что написать?
a_search	хотя нет найди мне статью						& quote

a_email	письмо												# что написать?
a_site	хотя нет открой мне сайт							& quote

a_email	письмо												# что написать?
a_alarm	хотя нет поставь будильник							& quote

a_email	письмо												# что написать?
a_balance	хотя нет покажи баланс							& quote


# cancellation, 3 s_change words

a_email	письмо												# что написать?
a_call	хотя нет лучше позвони васе							& quote

a_email	письмо												# что написать?
a_sms	хотя нет лучше напиши смс							& quote

a_email	письмо												# что написать?
a_email	хотя нет лучше напиши письмо						& quote

a_email	письмо												# что написать?
a_search	хотя нет лучше найди мне статью					& quote

a_email	письмо												# что написать?
a_site	хотя нет лучше открой мне сайт						& quote

a_email	письмо												# что написать?
a_alarm	хотя нет лучше поставь будильник					& quote

a_email	письмо												# что написать?
a_balance	хотя нет лучше покажи баланс					& quote


